use_frameworks!

platform :ios, '9.0'

target 'testPodLib_Example' do
  pod 'testPodLib', :path => '../'

  target 'testPodLib_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
